---
slug: :mikutter-adventure
depends:
  mikutter: change_account
  plugin:
  - gui
<<<<<<< HEAD
  - achievement
version: '0.0.2'
=======
version: '0.1.0'
>>>>>>> release/0.1.0
author: 
name: mikutter-adventure
description: adventure
